### ISSUE TITLE
Error: Yoloworld_ESAM_Zho: cannot import name 'packaging' from 'pkg_resources'  ((THANK YOU in advance))

### ISSUE THREAD

**Issue by piovis2023** [ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM#68]
Could someone kindly help me resolve this issue? 

Context:
I've downloaded and run one of the examples from this repo.
The following error occurs when it reaches the Yoloworld-Esam node. 
I have already installed and put the jit files.

Error occurred when executing Yoloworld_ESAM_Zho: cannot import name 'packaging' from 'pkg_resources' (C:\miniconda3\envs\comfyui4\Lib\site-packages\pkg_resources\__init__.py) File "C:\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 139, in yoloworld_esam_image YOLO_WORLD_MODEL.set_classes(categories) File "C:\miniconda3\envs\comfyui4\Lib\site-packages\inference\models\yolo_world\yolo_world.py", line 133, in set_classes self.model.set_classes(text) File "C:\miniconda3\envs\comfyui4\Lib\site-packages\ultralytics\models\yolo\model.py", line 97, in set_classes self.model.set_classes(classes) File "C:\miniconda3\envs\comfyui4\Lib\site-packages\ultralytics\nn\tasks.py", line 602, in set_classes import clip File "C:\miniconda3\envs\comfyui4\Lib\site-packages\clip\__init__.py", line 1, in from .clip import * File "C:\miniconda3\envs\comfyui4\Lib\site-packages\clip\clip.py", line 6, in from pkg_resources import packaging Error occurred when executing Yoloworld_ESAM_Zho: cannot import name 'packaging' from 'pkg_resources' (C:\miniconda3\envs\comfyui4\Lib\site-packages\pkg_resources\__init__.py) File "C:\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM\YOLO_WORLD_EfficientSAM.py", line 139, in yoloworld_esam_image YOLO_WORLD_MODEL.set_classes(categories) File "C:\miniconda3\envs\comfyui4\Lib\site-packages\inference\models\yolo_world\yolo_world.py", line 133, in set_classes self.model.set_classes(text) File "C:\miniconda3\envs\comfyui4\Lib\site-packages\ultralytics\models\yolo\model.py", line 97, in set_classes self.model.set_classes(classes) File "C:\miniconda3\envs\comfyui4\Lib\site-packages\ultralytics\nn\tasks.py", line 602, in set_classes import clip File "C:\miniconda3\envs\comfyui4\Lib\site-packages\clip\__init__.py", line 1, in from .clip import *

**Comment by spartacuskt** [comment]
the same for me

**Comment by feliperohde** [comment]
same here :(

**Comment by yankyankyank** [comment]
same here :((

**Comment by yhf1407** [comment]
同样

**Comment by piovis2023** [comment]
Creators details - I haven't had any response yet, but please share if any of you have better luck:
[@ZHOZHO672070](https://twitter.com/ZHOZHO672070)
https://space.bilibili.com/484366804
https://www.xiaohongshu.com/user/profile/63f11530000000001001e0c8?xhsshare=CopyLink&appuid=63f11530000000001001e0c8&apptime=1690528872
https://afdian.net/a/ZHOZHO

**Comment by OuticNZ** [comment]
the issue is caused by a new version of setuptools.  downgrade to below v70  

pip install setuptools==69.5.1

This resolve my issue

**Comment by yankyankyank** [comment]
> the issue is caused by a new version of setuptools. downgrade to below v70
> 
> pip install setuptools==69.5.1
> 
> This resolve my issue

thanks for sharing, i just tried and sadly still getting the error :(

**Comment by OuticNZ** [comment]
Did you install setuptools via the ComfyUI manager?  Install PIP Packages and putting in setuptools==69.5.1

**Comment by piovis2023** [comment]
@OuticNZ Excellent work. Worked for me. Thank you

**Comment by PolygonJuggler** [comment]
> > the issue is caused by a new version of setuptools. downgrade to below v70
> > pip install setuptools==69.5.1
> > This resolve my issue
> 
> thanks for sharing, i just tried and sadly still getting the error :(

Make sure your version of python is equal to: Python 3.11.9 (https://www.python.org/downloads/release/python-3119/)
It is supposed to work with lower versions as well, but in my case it didn't work with Python 3.10. 6. So I upgraded to 3.11.9 (higher versions won't work either) and after downgrading "setuptools" with the command suggested by "OuticNZ" it worked.

Remember to go inside "ComfyUI_windows_portable\python_embeded" folder and then run the command:

python.exe -m pip install setuptools==65.5.1
